version: '3'

services:
  dms:
    build:
      context: ./dms
    networks:
      - mynetwork

  url-shortener:
    build:
      context: ./main
    networks:
      - mynetwork
    ports:
      - "31.28.27.213:3000:3000"  # Локальный порт для доступа извне

  stats-collector:
    build:
      context: ./statistics_service
    networks:
      - mynetwork

networks:
  mynetwork:
